openapi: 3.2.0
info:
  title: TalentLMS Public Learning Paths API
  description: TalentLMS offers a range of API endpoints and resources designed to integrate TalentLMS with your internal systems seamlessly.
  version: 1.0.0
servers:
- url: https://your-domain.talentlms.com
security:
- apikeyAuth: []
tags:
- name: Learning Paths
paths:
  /api/v2/learning-paths:
    get:
      tags:
      - Learning Paths
      summary: Get learning paths
      description: '### **List all learning paths**


        Retrieves a paginated list of all learning paths in your TalentLMS account. Upon a successful request, the API returns a JSON response containing learning path objects, including their associated metadata and configuration details. Results are delivered in a paginated format to ensure efficient handling of large datasets. You can optionally filter the response by keyword or status.'
      parameters:
      - name: X-API-Version
        in: header
        schema:
          type: string
        example: '{{apiVersion}}'
      responses:
        200:
          description: Successful response
          content:
            application/json: {}
      operationId: getApiV2LearningPaths
      x-operation-id-source: derived
  /api/v2/learning-paths/:id:
    get:
      tags:
      - Learning Paths
      summary: Get learning path
      description: '### Get a learning path


        Retrieves the details of a specific learning path. To successfully fetch a learning path, include the learning path''s unique ID as a path parameter in the request URL. If the request is valid and the learning path exists, the API returns the full set of learning path details in the response.'
      parameters:
      - name: X-API-Version
        in: header
        schema:
          type: string
        example: '{{apiVersion}}'
      responses:
        200:
          description: Successful response
          content:
            application/json: {}
      operationId: getApiV2LearningPaths:id
      x-operation-id-source: derived
  /api/v2/learning-paths/enrollments:
    post:
      tags:
      - Learning Paths
      summary: Enroll a user to a learning path
      description: '### Enroll user to learning path


        Enrolls a user into a specific learning path. To create an enrollment, provide the user''s unique ID using the `user_id` attribute and the learning path''s unique ID using the `learning_path_id` attribute in the request body. If the request is valid and both the user and learning path exist, the API creates the enrollment and returns the enrollment details in the response.'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                user_id: <integer>
                learning_path_id: <integer>
      parameters:
      - name: X-API-Version
        in: header
        schema:
          type: string
        example: '{{apiVersion}}'
      responses:
        200:
          description: Successful response
          content:
            application/json: {}
      operationId: postApiV2LearningPathsEnrollments
      x-operation-id-source: derived
    delete:
      tags:
      - Learning Paths
      summary: Remove a user from a learning path
      description: '### Remove user from learning path


        Removes a user''s enrollment from a specific learning path. To successfully unenroll a user, provide the user''s unique ID using the `user_id` attribute and the learning path''s unique ID using the `learning_path_id` attribute in the request body. If the request is valid and the enrollment exists, the API deletes the enrollment and removes the user''s access to the learning path.'
      parameters:
      - name: X-API-Version
        in: header
        schema:
          type: string
        example: '{{apiVersion}}'
      responses:
        200:
          description: Successful response
          content:
            application/json: {}
      operationId: deleteApiV2LearningPathsEnrollments
      x-operation-id-source: derived
components:
  securitySchemes:
    apikeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
