openapi: 3.2.0
info:
  title: TalentLMS Public Category API
  description: TalentLMS offers a range of API endpoints and resources designed to integrate TalentLMS with your internal systems seamlessly.
  version: 1.0.0
servers:
- url: https://your-domain.talentlms.com
security:
- apikeyAuth: []
tags:
- name: Category
paths:
  /api/v2/categories:
    get:
      tags:
      - Category
      summary: List all categories
      description: '### List all categories


        Retrieves a paginated list of all categories in your TalentLMS account. Upon a successful request, the API returns a JSON response containing category objects, including their associated metadata and configuration details. Results are delivered in a paginated format to ensure efficient handling of large datasets.'
      parameters:
      - name: X-API-Version
        in: header
        schema:
          type: string
        example: '{{apiVersion}}'
      responses:
        200:
          description: Successful response
          content:
            application/json: {}
      operationId: getApiV2Categories
      x-operation-id-source: derived
  /api/v2/categories/:id:
    get:
      tags:
      - Category
      summary: Get a category
      description: '### Get a category


        Retrieves the full details of a specific category. To successfully fetch a category, include the category’s unique ID as a path parameter in the request URL. If the request is valid and the category exists, the API returns detailed information about the category, including its metadata and related configuration settings.'
      parameters:
      - name: X-API-Version
        in: header
        schema:
          type: string
        example: '{{apiVersion}}'
      responses:
        200:
          description: Successful response
          content:
            application/json: {}
      operationId: getApiV2Categories:id
      x-operation-id-source: derived
  /api/v2/categories/:id/purchase:
    post:
      tags:
      - Category
      summary: Purchase a course category
      description: '### Purchase a course category


        Provided the category ID in the endpoint''s path and the user ID in the request''s body a category can be purchased for this specific user. Optionally, you can specify the redirection url if the purchase is cancelled or succeeded and you can also provide a coupon key.'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                user_id: <integer>
                cancel_path: <string>
                return_path: <string>
                coupon: null
      parameters:
      - name: X-API-Version
        in: header
        schema:
          type: string
        example: '{{apiVersion}}'
      responses:
        200:
          description: Successful response
          content:
            application/json: {}
      operationId: postApiV2Categories:idPurchase
      x-operation-id-source: derived
components:
  securitySchemes:
    apikeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
