openapi: 3.2.0
info:
  title: TalentLMS Public Timeline API
  description: TalentLMS offers a range of API endpoints and resources designed to integrate TalentLMS with your internal systems seamlessly.
  version: 1.0.0
servers:
- url: https://your-domain.talentlms.com
security:
- apikeyAuth: []
tags:
- name: Timeline
paths:
  /api/v2/timeline:
    get:
      tags:
      - Timeline
      summary: Get timeline
      description: '### Get timeline


        Retrieve a chronological list of key platform events and user activities, including details such as event type, user, timestamp, and related entities, as a JSON array.'
      parameters:
      - name: X-API-Version
        in: header
        schema:
          type: string
        example: '{{apiVersion}}'
      responses:
        200:
          description: Successful response
          content:
            application/json: {}
      operationId: getApiV2Timeline
      x-operation-id-source: derived
components:
  securitySchemes:
    apikeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
