openapi: 3.2.0
info:
  title: TalentLMS Public Batch Actions API
  description: TalentLMS offers a range of API endpoints and resources designed to integrate TalentLMS with your internal systems seamlessly.
  version: 1.0.0
servers:
- url: https://your-domain.talentlms.com
security:
- apikeyAuth: []
tags:
- name: Batch Actions
  description: This section introduces endpoints that perform bulk actions. After invoking any of the below endpoints, their response includes a background task ID.. You can use the `GET api/v2/tasks/:id` endpoint to track the progress of the action. For each request, the limit of items passed inside the body is 100.
paths:
  /api/v2/batch/courses:
    post:
      tags:
      - Batch Actions
      summary: Upsert Courses
      description: '### Upsert courses


        Provide the course name, code, description and status to create new courses or update an existing ones. You can update a course by providing either its code or id.'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                courses:
                - name: <string>
                  code: <string>
                  description: <string>
                  is_active: <boolean>
                - name: <string>
                  code: <string>
                  description: <string>
                  is_active: <boolean>
      parameters:
      - name: X-API-Version
        in: header
        schema:
          type: string
        example: '{{apiVersion}}'
      responses:
        200:
          description: Successful response
          content:
            application/json: {}
      operationId: postApiV2BatchCourses
      x-operation-id-source: derived
  /api/v2/batch/enrollments:
    post:
      tags:
      - Batch Actions
      summary: Course Enrollments
      description: '### Course Enrollments


        Creates multiple course enrollments in a single request.


        Use this endpoint to mass assign users to courses by providing an array of course_id and user_id pairs in the request body. If the request is valid, the API processes each enrollment and returns the corresponding results.


        This endpoint is ideal for bulk operations and large-scale user-course assignments.'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                enrollments:
                - course_id: <integer>
                  user_id: <integer>
                - course_id: <integer>
                  user_id: <integer>
      parameters:
      - name: X-API-Version
        in: header
        schema:
          type: string
        example: '{{apiVersion}}'
      responses:
        200:
          description: Successful response
          content:
            application/json: {}
      operationId: postApiV2BatchEnrollments
      x-operation-id-source: derived
  /api/v2/batch/users:
    post:
      tags:
      - Batch Actions
      summary: Upsert Users
      description: 'Creates or updates multiple users in a single request.


        Use this endpoint to mass create or update users by providing an array of user objects in the request body. Each object may include core user attributes (such as login, name, email, and status) as well as custom user fields. If a user already exists, the body needs to have the corresponding id and their information will be updated. If the user does not exist, a new user is created.


        This endpoint is ideal for bulk user provisioning, HRIS synchronization, and large-scale user updates, including custom field updates.'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                users:
                - login: <string>
                  name: <string>
                  surname: <string>
                  email: <string>
                  status: <string>
                  custom_field_1: <string>
                  custom_field_2: <string>
                  custom_field_4: <string>
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: Accept
        in: header
        schema:
          type: string
        example: application/json
      - name: X-API-Version
        in: header
        schema:
          type: string
        example: '{{apiVersion}}'
      responses:
        200:
          description: Successful response
          content:
            application/json: {}
      operationId: postApiV2BatchUsers
      x-operation-id-source: derived
components:
  securitySchemes:
    apikeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
