openapi: 3.2.0
info:
  title: TalentLMS Public Portal API
  description: TalentLMS offers a range of API endpoints and resources designed to integrate TalentLMS with your internal systems seamlessly.
  version: 1.0.0
servers:
- url: https://your-domain.talentlms.com
security:
- apikeyAuth: []
tags:
- name: Portal
paths:
  /api/v2/statistics:
    get:
      tags:
      - Portal
      summary: Get portal's statistics
      description: '### Get portal''s statistics


        Retrieve platform-wide statistics, such as total users, courses, categories, groups, branches, and configuration details, by sending an authenticated GET request to this endpoint and receiving a report as a JSON object.'
      parameters:
      - name: X-API-Version
        in: header
        schema:
          type: string
        example: '{{apiVersion}}'
      responses:
        200:
          description: Successful response
          content:
            application/json: {}
      operationId: getApiV2Statistics
      x-operation-id-source: derived
  /api/v2/health:
    get:
      tags:
      - Portal
      summary: Health check
      operationId: healthCheck
      responses:
        200:
          description: OK
      security: []
components:
  securitySchemes:
    apikeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
