openapi: 3.2.0
info:
  title: TalentLMS Public Unit API
  description: TalentLMS offers a range of API endpoints and resources designed to integrate TalentLMS with your internal systems seamlessly.
  version: 1.0.0
servers:
- url: https://your-domain.talentlms.com
security:
- apikeyAuth: []
tags:
- name: Unit
paths:
  /api/v2/results:
    get:
      tags:
      - Unit
      summary: Get user's test/survey answers
      description: '### Get user''s test/survey answers


        Retrieve detailed test/survey results for a specific user and unit, including status, score, completion date, and a breakdown of answers for each question.'
      parameters:
      - name: X-API-Version
        in: header
        schema:
          type: string
        example: '{{apiVersion}}'
      - name: unit_id
        in: query
        schema:
          type: string
        example: <integer>
      - name: user_id
        in: query
        schema:
          type: string
        example: <integer>
      responses:
        200:
          description: Successful response
          content:
            application/json: {}
      operationId: getApiV2Results
      x-operation-id-source: derived
  /api/v2/units/:id/sessions:
    get:
      tags:
      - Unit
      summary: Get ILT unit's sessions
      description: '### Get ILT unit''s sessions


        Retrieves the scheduled sessions of a specific Instructor-Led Training (ILT) unit. To successfully fetch session details, include the ILT unit’s unique ID as a path parameter in the request URL. If the request is valid and the unit exists, the API returns a JSON response containing information about all associated sessions, including their schedule and related metadata.'
      parameters:
      - name: X-API-Version
        in: header
        schema:
          type: string
        example: '{{apiVersion}}'
      responses:
        200:
          description: Successful response
          content:
            application/json: {}
      operationId: getApiV2Units:idSessions
      x-operation-id-source: derived
components:
  securitySchemes:
    apikeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
