openapi: 3.2.0
info:
  title: TalentLMS Public Branch API
  description: TalentLMS offers a range of API endpoints and resources designed to integrate TalentLMS with your internal systems seamlessly.
  version: 1.0.0
servers:
- url: https://your-domain.talentlms.com
security:
- apikeyAuth: []
tags:
- name: Branch
paths:
  /api/v2/branches:
    get:
      tags:
      - Branch
      summary: List all branches
      description: '### List all branches


        Retrieves a paginated list of all branches in your TalentLMS account. Upon a successful request, the API returns a JSON response containing branch objects, including their associated metadata and configuration details. Results are delivered in a paginated format to ensure efficient handling of large datasets.'
      parameters:
      - name: X-API-Version
        in: header
        schema:
          type: string
        example: '{{apiVersion}}'
      responses:
        200:
          description: Successful response
          content:
            application/json: {}
      operationId: getApiV2Branches
      x-operation-id-source: derived
    post:
      tags:
      - Branch
      summary: Create a branch
      description: '### Create a branch


        Creates a new branch in your TalentLMS account. To successfully create a branch, provide the required branch attributes in the request body as a JSON object. If the request is valid, the API creates the branch and returns the newly created branch details, including its unique identifier.'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: <string>
                description: <string>
                default_locale: <string>
      parameters:
      - name: X-API-Version
        in: header
        schema:
          type: string
        example: '{{apiVersion}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        200:
          description: Successful response
          content:
            application/json: {}
      operationId: postApiV2Branches
      x-operation-id-source: derived
  /api/v2/branches/:id:
    get:
      tags:
      - Branch
      summary: Get a branch
      description: '### Get a branch


        Retrieves the full details of a specific branch. To successfully fetch a branch, include the branch’s unique ID as a path parameter in the request URL. If the request is valid and the branch exists, the API returns detailed information about the branch, including its configuration settings and metadata.'
      parameters:
      - name: X-API-Version
        in: header
        schema:
          type: string
        example: '{{apiVersion}}'
      responses:
        200:
          description: Successful response
          content:
            application/json: {}
      operationId: getApiV2Branches:id
      x-operation-id-source: derived
    delete:
      tags:
      - Branch
      summary: Delete a branch
      description: '### Delete a branch


        Permanently deletes a specific branch from your TalentLMS account. To successfully remove a branch, include the branch’s unique ID as a path parameter in the request URL. If the request is valid and the branch exists, the API deletes the branch and returns a **204 No Content** response upon success.'
      parameters:
      - name: X-API-Version
        in: header
        schema:
          type: string
        example: '{{apiVersion}}'
      responses:
        200:
          description: Successful response
          content:
            application/json: {}
      operationId: deleteApiV2Branches:id
      x-operation-id-source: derived
  /api/v2/branch-users:
    post:
      tags:
      - Branch
      summary: Add user to branch
      description: '### Add a user to a branch


        Associates a user with a specific branch. To successfully add a user to a branch, provide the branch’s unique ID using the branch_id attribute and the user’s unique ID using the user_id attribute in the request body. If the request is valid and both the user and branch exist, the API creates the association and returns the corresponding branch-user relationship details.'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                branch_id: <integer>
                user_id: <integer>
      parameters:
      - name: X-API-Version
        in: header
        schema:
          type: string
        example: '{{apiVersion}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        200:
          description: Successful response
          content:
            application/json: {}
      operationId: postApiV2BranchUsers
      x-operation-id-source: derived
    delete:
      tags:
      - Branch
      summary: Remove user from branch
      description: '### Remove user from branch


        Removes a user from a specific branch. To successfully remove a user from a branch, provide the branch’s unique ID using the branch_id attribute and the user’s unique ID using the user_id attribute. If the request is valid and the association exists, the API deletes the branch-user relationship and returns a **204 No Content** response upon success.'
      parameters:
      - name: X-API-Version
        in: header
        schema:
          type: string
        example: '{{apiVersion}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        200:
          description: Successful response
          content:
            application/json: {}
      operationId: deleteApiV2BranchUsers
      x-operation-id-source: derived
  /api/v2/branch-courses:
    post:
      tags:
      - Branch
      summary: Add course to branch
      description: '### Add course to branch


        Associates a course with a specific branch. To successfully assign a course to a branch, provide the course’s unique ID using the course_id attribute and the branch’s unique ID using the branch_id attribute in the request body. If the request is valid and both the course and branch exist, the API creates the association and returns the corresponding branch-course relationship details.'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                branch_id: <integer>
                course_id: <integer>
      parameters:
      - name: X-API-Version
        in: header
        schema:
          type: string
        example: '{{apiVersion}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        200:
          description: Successful response
          content:
            application/json: {}
      operationId: postApiV2BranchCourses
      x-operation-id-source: derived
    delete:
      tags:
      - Branch
      summary: Remove course from branch
      description: '### Remove course from branch


        Removes a course from a specific branch. To successfully remove a course from a branch, provide the course''s unique ID using the `course_id` attribute and the branch''s unique ID using the `branch_id` attribute in the request body. If the request is valid and the association exists, the API deletes the branch-course relationship and returns a 204 No Content response upon success.'
      parameters:
      - name: X-API-Version
        in: header
        schema:
          type: string
        example: '{{apiVersion}}'
      responses:
        200:
          description: Successful response
          content:
            application/json: {}
      operationId: deleteApiV2BranchCourses
      x-operation-id-source: derived
  /api/v2/branches/{id}/status:
    put:
      tags:
      - Branch
      summary: Change branch status
      description: '### Change branch status. Activates or deactivates a specific branch. To update the branch status, include the branch''s unique ID as a path parameter in the request URL and provide a boolean value for the is_active attribute in the request body. If the request is valid and the branch exists, the API updates the branch''s status accordingly and returns the updated branch details.'
      operationId: updateBranchStatus
      parameters:
      - name: id
        in: path
        description: The ID of the branch
        required: true
        schema:
          type: integer
      - name: X-API-Version
        in: header
        required: false
        schema:
          type: string
        example: '{{apiVersion}}'
      - name: Content-Type
        in: header
        required: false
        schema:
          type: string
        example: application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                is_active:
                  type: boolean
                  example: true
              type: object
      responses:
        204:
          description: Successful response
components:
  securitySchemes:
    apikeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
