openapi: 3.2.0
info:
  title: TalentLMS Public Task API
  description: TalentLMS offers a range of API endpoints and resources designed to integrate TalentLMS with your internal systems seamlessly.
  version: 1.0.0
servers:
- url: https://your-domain.talentlms.com
security:
- apikeyAuth: []
tags:
- name: Task
paths:
  /api/v2/tasks/:id:
    get:
      tags:
      - Task
      summary: Get task's status and progress
      description: '### Get task''s status and progress


        Retrieves the current status and progress of a background process task. To successfully fetch task details, include the task’s unique ID as a path parameter in the request URL. If the request is valid and the task exists, the API returns information about the task’s execution status and completion progress. This endpoint is typically used to monitor long-running or asynchronous operations.'
      parameters:
      - name: X-API-Version
        in: header
        schema:
          type: string
        example: '{{apiVersion}}'
      responses:
        200:
          description: Successful response
          content:
            application/json: {}
      operationId: getApiV2Tasks:id
      x-operation-id-source: derived
components:
  securitySchemes:
    apikeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
